### ISSUE TITLE
Transfer repo ownership to EverTrue

### ISSUE THREAD

**Issue by jeffbyrnes** [jeffbyrnes/exhibitor-cookbook#33]
@jakedavis seeing as we’ve taken over the [`zookeeper` cookbook](/evertrue/zookeeper-cookbook), I was wondering if you’d like to transfer this one to us, as well? We already own the Supermarket releases.

**Comment by jakedavis** [comment]
Good lord how did I miss this notification for a whole week? Sorry, taking care of this now.

**Comment by jakedavis** [comment]
Sent the request to ya. Lemme know if there's anything else I can do.

**Comment by jeffbyrnes** [comment]
@jakedavis awesome, thanks so much! No worries on the timeline 😄
